import type { Package } from "@/lib/types";

export const MLBB_ID = "game_mlbb";

export const packages: Package[] = [
  {
    id: "pkg_mlbb_15",
    gameId: MLBB_ID,
    name: "Weekly Pass",
    displayName: "Weekly Pass",
    priceKs: 7000,
    smileGoodsId: "16642",
    featured: true,
    isActive: true,
    sortOrder: 0,
    offPercent: 0,
    offKs: 400,
    smileCoin: 76,
  },
  {
    id: "pkg_mlbb_1",
    gameId: MLBB_ID,
    name: "Weekly Elite Bundle",
    displayName: "Weekly Elite Bundle",
    priceKs: 3600,
    smileGoodsId: "26555",
    featured: false,
    isActive: true,
    sortOrder: 1,
    offPercent: 0,
    offKs: 0,
    smileCoin: 39,
  },
  {
    id: "pkg_mlbb_2",
    gameId: MLBB_ID,
    name: "Monthly Epic Bundle",
    displayName: "Monthly Epic Bundle",
    priceKs: 18100,
    smileGoodsId: "26556",
    featured: false,
    isActive: true,
    sortOrder: 2,
    offPercent: 0,
    offKs: 0,
    smileCoin: 196.5,
  },
  {
    id: "pkg_mlbb_3",
    gameId: MLBB_ID,
    name: "Diamond×50 +5",
    displayName: "50+5",
    priceKs: 3600,
    smileGoodsId: "22590",
    featured: false,
    isActive: true,
    sortOrder: 3,
    offPercent: 0,
    offKs: 0,
    smileCoin: 39,
  },
  {
    id: "pkg_mlbb_4",
    gameId: MLBB_ID,
    name: "Diamond×150 +15",
    displayName: "150+15",
    priceKs: 10800,
    smileGoodsId: "22591",
    featured: false,
    isActive: true,
    sortOrder: 4,
    offPercent: 0,
    offKs: 0,
    smileCoin: 116.9,
  },
  {
    id: "pkg_mlbb_5",
    gameId: MLBB_ID,
    name: "Diamond×250 +25",
    displayName: "250+25",
    priceKs: 17200,
    smileGoodsId: "22592",
    featured: false,
    isActive: true,
    sortOrder: 5,
    offPercent: 0,
    offKs: 0,
    smileCoin: 187.5,
  },
  {
    id: "pkg_mlbb_6",
    gameId: MLBB_ID,
    name: "Diamond×500 +65",
    displayName: "500+65",
    priceKs: 35400,
    smileGoodsId: "22593",
    featured: false,
    isActive: true,
    sortOrder: 6,
    offPercent: 0,
    offKs: 0,
    smileCoin: 385,
  },
  {
    id: "pkg_mlbb_7",
    gameId: MLBB_ID,
    name: "Diamond×78 +8",
    displayName: "78+8",
    priceKs: 5700,
    smileGoodsId: "13",
    featured: false,
    isActive: true,
    sortOrder: 7,
    offPercent: 0,
    offKs: 0,
    smileCoin: 61.5,
  },
  {
    id: "pkg_mlbb_8",
    gameId: MLBB_ID,
    name: "Diamond×156 +16",
    displayName: "156+16",
    priceKs: 11200,
    smileGoodsId: "23",
    featured: false,
    isActive: true,
    sortOrder: 8,
    offPercent: 0,
    offKs: 0,
    smileCoin: 122,
  },
  {
    id: "pkg_mlbb_9",
    gameId: MLBB_ID,
    name: "Diamond×234 +23",
    displayName: "234+23",
    priceKs: 16300,
    smileGoodsId: "25",
    featured: false,
    isActive: true,
    sortOrder: 9,
    offPercent: 0,
    offKs: 0,
    smileCoin: 176.7,
  },
  {
    id: "pkg_mlbb_10",
    gameId: MLBB_ID,
    name: "Diamond×625 +81",
    displayName: "625+81",
    priceKs: 44200,
    smileGoodsId: "26",
    featured: false,
    isActive: true,
    sortOrder: 10,
    offPercent: 0,
    offKs: 0,
    smileCoin: 480,
  },
  {
    id: "pkg_mlbb_11",
    gameId: MLBB_ID,
    name: "Diamond×1860 +335",
    displayName: "1860+335",
    priceKs: 133700,
    smileGoodsId: "27",
    featured: false,
    isActive: true,
    sortOrder: 11,
    offPercent: 0,
    offKs: 0,
    smileCoin: 1453,
  },
  {
    id: "pkg_mlbb_12",
    gameId: MLBB_ID,
    name: "Diamond×3099 +589",
    displayName: "3099+589",
    priceKs: 223000,
    smileGoodsId: "28",
    featured: false,
    isActive: true,
    sortOrder: 12,
    offPercent: 0,
    offKs: 0,
    smileCoin: 2424,
  },
  {
    id: "pkg_mlbb_13",
    gameId: MLBB_ID,
    name: "Diamond×4649 +883",
    displayName: "4649+883",
    priceKs: 336700,
    smileGoodsId: "29",
    featured: false,
    isActive: true,
    sortOrder: 13,
    offPercent: 0,
    offKs: 0,
    smileCoin: 3660,
  },
  {
    id: "pkg_mlbb_14",
    gameId: MLBB_ID,
    name: "Diamond×7740 +1548",
    displayName: "7740+1548",
    priceKs: 547000,
    smileGoodsId: "30",
    featured: false,
    isActive: true,
    sortOrder: 14,
    offPercent: 0,
    offKs: 0,
    smileCoin: 6079,
  },
  {
    id: "pkg_mlbb_16",
    gameId: MLBB_ID,
    name: "Twilight Pass",
    displayName: "Twilight Pass",
    priceKs: 36000,
    smileGoodsId: "33",
    featured: true,
    isActive: true,
    sortOrder: 15,
    offPercent: 0,
    offKs: 0,
    smileCoin: 402.5,
  },
];
