"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";

interface TwoFactorSetupResponse {
  enabled: boolean;
  secret?: string;
  otpauthUrl?: string;
  qrCodeSvg?: string;
}

export default function AdminSecurityPage() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<TwoFactorSetupResponse | null>(null);
  const [verifyCode, setVerifyCode] = useState("");
  const [disableCode, setDisableCode] = useState("");
  const [copied, setCopied] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const loadStatus = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await api<TwoFactorSetupResponse>("/api/admin/2fa");
      setData(res);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load 2FA status");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadStatus();
  }, []);

  const handleActivate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!data?.secret || verifyCode.length !== 6) return;
    setBusy(true);
    setError("");
    setSuccess("");
    try {
      const res = await api<{ ok: boolean; message: string }>("/api/admin/2fa", {
        method: "POST",
        body: JSON.stringify({
          secret: data.secret,
          code: verifyCode,
        }),
      });
      setSuccess(res.message || "Two-Factor Authentication activated successfully!");
      setVerifyCode("");
      await loadStatus();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Activation failed");
    } finally {
      setBusy(false);
    }
  };

  const handleDisable = async (e: React.FormEvent) => {
    e.preventDefault();
    if (disableCode.length !== 6) return;
    setBusy(true);
    setError("");
    setSuccess("");
    try {
      const res = await api<{ ok: boolean; message: string }>("/api/admin/2fa", {
        method: "DELETE",
        body: JSON.stringify({ code: disableCode }),
      });
      setSuccess(res.message || "Two-Factor Authentication disabled.");
      setDisableCode("");
      await loadStatus();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to disable 2FA");
    } finally {
      setBusy(false);
    }
  };

  const copySecret = () => {
    if (!data?.secret) return;
    void navigator.clipboard.writeText(data.secret);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading && !data) {
    return (
      <div style={{ padding: "40px 0", textAlign: "center", color: "var(--text-2)" }}>
        <div className="spinner" style={{ margin: "0 auto 16px" }} />
        <p>Loading security settings...</p>
      </div>
    );
  }

  return (
    <>
      <div className="page-h">
        <div>
          <h2>Security & Two-Factor Authentication</h2>
          <p>Protect your admin control panel with Google Authenticator TOTP verification.</p>
        </div>
      </div>

      {error ? <p className="err" style={{ marginBottom: 16 }}>{error}</p> : null}
      {success ? (
        <div
          style={{
            background: "#e6f7ef",
            color: "#0f7f4e",
            border: "1px solid #c2eed9",
            padding: "12px 16px",
            borderRadius: "8px",
            fontSize: "13px",
            fontWeight: "600",
            marginBottom: "16px",
          }}
        >
          {success}
        </div>
      ) : null}

      {data?.enabled ? (
        <div className="dash-card" style={{ maxWidth: 640 }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}>
            <div>
              <div className="dash-card-title">Google Authenticator (2FA)</div>
              <div className="dash-card-subtitle">Two-Factor Authentication is currently active</div>
            </div>
            <span className="status-badge badge-success" style={{ padding: "6px 12px", fontSize: "12px" }}>
              Active & Protected
            </span>
          </div>

          <p style={{ fontSize: "13px", color: "var(--text-2)", lineHeight: "1.6", marginBottom: "20px" }}>
            Every sign-in attempt requires your primary password and the rolling 6-digit verification code
            generated by your Google Authenticator app.
          </p>

          <div style={{ borderTop: "1px solid var(--border)", paddingTop: "18px" }}>
            <div style={{ fontSize: "13px", fontWeight: "700", color: "var(--navy)", marginBottom: "8px" }}>
              Disable Two-Factor Authentication
            </div>
            <p style={{ fontSize: "12px", color: "var(--text-2)", marginBottom: "14px" }}>
              To turn off 2FA, enter the current 6-digit code from your authenticator app below:
            </p>
            <form onSubmit={handleDisable} style={{ display: "flex", gap: "10px", alignItems: "center" }}>
              <input
                type="text"
                inputMode="numeric"
                pattern="[0-9]*"
                maxLength={6}
                value={disableCode}
                onChange={(e) => setDisableCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                placeholder="000000"
                style={{
                  width: 140,
                  textAlign: "center",
                  fontSize: "16px",
                  letterSpacing: "0.15em",
                  fontFamily: "monospace",
                  fontWeight: "700",
                }}
                required
              />
              <button
                type="submit"
                className="btn-sec"
                style={{ color: "#c5221f", borderColor: "#fce8e6" }}
                disabled={busy || disableCode.length !== 6}
              >
                {busy ? "Disabling…" : "Disable 2FA"}
              </button>
            </form>
          </div>
        </div>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px", maxWidth: 900 }}>
          {/* Step 1: Scan QR Code */}
          <div className="dash-card">
            <div className="dash-card-title" style={{ marginBottom: 4 }}>
              Step 1: Scan QR Code
            </div>
            <div className="dash-card-subtitle" style={{ marginBottom: 16 }}>
              Open Google Authenticator on your mobile device and scan:
            </div>

            {data?.qrCodeSvg ? (
              <div
                style={{
                  display: "grid",
                  placeItems: "center",
                  padding: "16px 0",
                  background: "var(--bg)",
                  borderRadius: "12px",
                  marginBottom: "16px",
                }}
                dangerouslySetInnerHTML={{ __html: data.qrCodeSvg }}
              />
            ) : null}

            <div style={{ fontSize: "12px", color: "var(--text-2)", marginBottom: "6px" }}>
              Or enter this setup key manually:
            </div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                background: "var(--bg)",
                padding: "8px 12px",
                borderRadius: "8px",
                fontFamily: "monospace",
                fontSize: "13px",
                fontWeight: "700",
                color: "var(--navy)",
              }}
            >
              <span>{data?.secret || "—"}</span>
              <button
                type="button"
                onClick={copySecret}
                style={{
                  background: "transparent",
                  border: 0,
                  fontSize: "11px",
                  fontWeight: "700",
                  color: "var(--brand-dark)",
                  cursor: "pointer",
                }}
              >
                {copied ? "Copied" : "Copy Key"}
              </button>
            </div>
          </div>

          {/* Step 2: Verify & Activate */}
          <div className="dash-card">
            <div className="dash-card-title" style={{ marginBottom: 4 }}>
              Step 2: Verify & Activate
            </div>
            <div className="dash-card-subtitle" style={{ marginBottom: 20 }}>
              Enter the 6-digit code shown in your app to confirm setup:
            </div>

            <form onSubmit={handleActivate}>
              <label className="field" style={{ marginBottom: 20 }}>
                6-Digit Authenticator Code
                <input
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={6}
                  value={verifyCode}
                  onChange={(e) => setVerifyCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                  placeholder="000000"
                  style={{
                    textAlign: "center",
                    fontSize: "22px",
                    letterSpacing: "0.25em",
                    fontFamily: "monospace",
                    fontWeight: "700",
                    height: "48px",
                  }}
                  required
                />
              </label>

              <button
                type="submit"
                className="btn"
                disabled={busy || verifyCode.length !== 6}
                style={{ width: "100%" }}
              >
                {busy ? "Activating…" : "Activate Two-Factor Authentication"}
              </button>
            </form>

            <div style={{ marginTop: "24px", padding: "14px", background: "var(--bg)", borderRadius: "8px" }}>
              <div style={{ fontSize: "12px", fontWeight: "700", color: "var(--navy)", marginBottom: "4px" }}>
                Compatible Apps
              </div>
              <p style={{ fontSize: "11px", color: "var(--text-2)", lineHeight: "1.5" }}>
                Works with Google Authenticator, Microsoft Authenticator, 1Password, Authy, or any RFC 6238 TOTP client.
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
